### ISSUE TITLE
Bug? Bad indentation?

### ISSUE THREAD

**Issue by srfrnk** [pstaender/mongraph#12]
In file mongraph/src/mongraphMongoosePlugin.coffee at line 27 there's this:
 schema.add
      _node_id: Number
      # add an empty object as placeholder for relationships, use is optional
      schema.add _relationships: {}

Which transpiles into:
schema.add({
      _node_id: Number
    }, schema.add({
      _relationships: {}
    }));

This means by mongoose API that you add _relationships as a prefix.... unless I'm missing something....

Can anyone clarify? Is it intentional or just a mistaken indentation issue?

**Comment by pstaender** [comment]
@srfrnk , you can define custom fields to your document record "schema":

```coffeescript
schema.add(_relationships: {})
```

But it's not a prefix or something. I just choosed the underscore naming to show, that this record attribute is kind of "hidden" data. `_relationships` is an attribute which can be a (nested) JSON object. Could I answer your question?
